version: '2'
services:
  express-books-api:
    image: node:10.15.3-alpine
    depends_on:
      - express-books-db
    container_name: express-books-api
    volumes:
      - express_books_api_node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    environment:
      # D
      - DEBUG=false
      # L
      - LOGGER_LEVEL=warn
      # M
      - MONGO_DB_AUTO_INDEX=true
      - MONGO_DB_BUFFER_COMMANDS=false
      - MONGO_DB_DEBUG=false
      - MONGO_DB_HOST=express-books-db
      - MONGO_DB_NAME=books-dev
      - MONGO_DB_PORT=27017
      # N
      - NODE_ENV=development
      # S
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    command: yarn start
  express-books-db:
    image: mongo
    container_name: express-books-db
    volumes:
      - express_books_api_mongo_db:/data/db
    ports:
      - 27017:27017
volumes:
  express_books_api_node_modules:
    external: true
  express_books_api_mongo_db:
    external: true
