version: '2'

services:
  base:
    image: node:10.15.3-alpine
    volumes:
      - books_node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
  
  install:
    extends:
      service: base
    command: yarn install

volumes:
  books_node_modules:
    external: true