version: '2'

services:
  base:
    image: node:10.15.3-alpine
    volumes:
      - books_node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080

  dev:
    extends:
      service: base
    command: yarn dev
    ports:
      - 8080:8080

  debug:
    extends:
      service: base
    command: yarn debug
    ports:
      - 8080:8080
      - 9229:9229

volumes:
  books_node_modules:
    external: true